[tool.poetry]
name = "llama-testing"
version = "0.1.0"
description = ""
authors = [
    "Mike O'Donnell"
]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
vllm = "^0.6.6post1"
fastapi = "^0.115.7"
uvicorn = "^0.34.0"
